# Generated by Django 2.2.3 on 2019-09-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Metier',
        ),
    ]
